### ISSUE TITLE
[Question] Height of PCB and JLCPCB part list

### ISSUE THREAD

**Issue by C4illin** [wareya/DIY-Gaming-Mouse#3]
What height should the PCB be? 1.6mm?

**Comment by wareya** [comment]
Yep, 1.6mm standard!

**Comment by C4illin** [comment]
Thank you!

Do you have any JLCPCB part list? The project.db seems to be unpopulated

**Comment by wareya** [comment]
It seems to contain the right data for me:

![image](https://github.com/wareya/DIY-Gaming-Mouse/assets/585488/0723c8d1-7f9d-486f-85cc-f819d1c1fbf9)

The plugin that uses project.db is https://github.com/Bouni/kicad-jlcpcb-tools

**Comment by C4illin** [comment]
Ohh didn't know about that plugin. It was only missing R40 but that one was easy to find :) Thanks for the help!

**Comment by wareya** [comment]
Make sure you don't do what I did and accidentally get a 3.9k ohm resistor instead of a 39 ohm one! The 39 ohm ones don't show up in the 'Basic' catalog.

**Comment by C4illin** [comment]
Yeah if it was something I learned from the video it was that 😄
I actually used that frame in the video to try matching so I got all component right, before asking here :)

I was thinking of taking the C137630 from extended catalog.

**Comment by wareya** [comment]
Yep, the C137630 should work!

**Comment by C4illin** [comment]
Thanks for all the help!

**Comment by C4illin** [comment]
Hello, in the DB it says to use C22775 for R3, R4 but C22775 is 100 ohm and not 27 ohm as specified, what is correct?

**Comment by wareya** [comment]
Those would be the USB data line impedance control resistors. I think putting in 100 ohm resistors is probably a mistake on my part.

Their exact resistance probably doesn't matter too much. 27.4 ohms is the value suggested/specified by the rp2040 hardware design docs. I would expect anything between 10 and 50 to work in practice. The target resistance for the entire data line according to the usb spec is 90 ohms, and real usb parent devices are more generous than that in practice.

I'll amend the part selection and double check everything again when I have a few spare hours.

**Comment by C4illin** [comment]
100 ohm is much cheaper on jlcpcb ;) 

Thanks for the confirmation! Will order my pcb today

**Comment by wareya** [comment]
Looks like I did indeed end up using 100 ohm resistors (01A):

![IMG_20240602_072003.jpg](https://github.com/wareya/DIY-Gaming-Mouse/assets/585488/e572f66a-b57d-4357-9015-f8d7b778acef)

So yeah, should still work! Unless you have a particularly picky machine.
